In [4]:
import numpy as np

In [6]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
for row in a:
    for i in row:
        print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [10]:
for cell in a.flatten():
    print(cell, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [26]:
# c= 0
for x in np.nditer(a, order="c", flags=['external_loop']):
    print(x)
#     c+=x
# print(f"\nthe Sum of this array is {c}")

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
a.ndim

2

In [33]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=x*x

In [41]:
a

array([[        0,         1,       256,      6561],
       [    65536,    390625,   1679616,   5764801],
       [ 16777216,  43046721, 100000000, 214358881]])

In [56]:
b = np.arange(3,15,4).reshape(3,1)

In [47]:
b

array([[ 3],
       [ 7],
       [11]])

In [57]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
256 3
6561 3
65536 7
390625 7
1679616 7
5764801 7
16777216 11
43046721 11
100000000 11
214358881 11


In [76]:
d = np.arange(10).reshape(2,5)
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
d = np.empty((2,3))
d

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

In [80]:
e = np.arange(12).reshape(2,3,2)
e

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [85]:
f = np.arange(100).reshape(10,10)
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])