In [1]:
import numpy as np

In [2]:
a = np.array([[1,5,6],[4,5,7]])
a

array([[1, 5, 6],
       [4, 5, 7]])

In [3]:
b = np.array([[2,4,8],[9,7,6]])
b

array([[2, 4, 8],
       [9, 7, 6]])

In [5]:
a*b

array([[ 2, 20, 48],
       [36, 35, 42]])

In [8]:
c = np.arange(1000).reshape(10,10,10)
c[0]+c[1]

array([[100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198],
       [200, 202, 204, 206, 208, 210, 212, 214, 216, 218],
       [220, 222, 224, 226, 228, 230, 232, 234, 236, 238],
       [240, 242, 244, 246, 248, 250, 252, 254, 256, 258],
       [260, 262, 264, 266, 268, 270, 272, 274, 276, 278],
       [280, 282, 284, 286, 288, 290, 292, 294, 296, 298]])

In [9]:
a**2

array([[ 1, 25, 36],
       [16, 25, 49]], dtype=int32)

In [23]:
b = a >= 5
a[b] = 6
a

array([[1, 6, 6],
       [4, 6, 6]])

In [25]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A.dot(B)

array([[5, 4],
       [3, 4]])

In [35]:
A

array([[8, 8],
       [0, 8]])

In [27]:
A

array([[1, 1],
       [0, 1]])

In [32]:
A

array([[8, 8],
       [0, 8]])

In [31]:
A

array([[8, 8],
       [0, 8]])

In [41]:
A+=B
A

array([[20,  8],
       [18, 32]])

In [44]:
A[::-1]

array([[18, 32],
       [20,  8]])

In [55]:
first = np.array([2,4,5,6,7,8,9,33,4,6,7])
b = first>=2
first[b] = 0
first

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Here This is Second Session

##Here This is Second Session