In [1]:
import numpy as np

In [2]:
a = np.array([[1,5,6],[4,5,7]])
a

array([[1, 5, 6],
       [4, 5, 7]])

In [3]:
b = np.array([[2,4,8],[9,7,6]])
b

array([[2, 4, 8],
       [9, 7, 6]])

In [5]:
a*b

array([[ 2, 20, 48],
       [36, 35, 42]])

In [24]:
c = np.arange(1000).reshape(10,10,10)
for row in c:
    for i in row:
        print(i, end="")
        for k in i:
            if k%10==0:
                print('\n')
    print(' \n')
#     print(c, end="")

[0 1 2 3 4 5 6 7 8 9]

[10 11 12 13 14 15 16 17 18 19]

[20 21 22 23 24 25 26 27 28 29]

[30 31 32 33 34 35 36 37 38 39]

[40 41 42 43 44 45 46 47 48 49]

[50 51 52 53 54 55 56 57 58 59]

[60 61 62 63 64 65 66 67 68 69]

[70 71 72 73 74 75 76 77 78 79]

[80 81 82 83 84 85 86 87 88 89]

[90 91 92 93 94 95 96 97 98 99]

 

[100 101 102 103 104 105 106 107 108 109]

[110 111 112 113 114 115 116 117 118 119]

[120 121 122 123 124 125 126 127 128 129]

[130 131 132 133 134 135 136 137 138 139]

[140 141 142 143 144 145 146 147 148 149]

[150 151 152 153 154 155 156 157 158 159]

[160 161 162 163 164 165 166 167 168 169]

[170 171 172 173 174 175 176 177 178 179]

[180 181 182 183 184 185 186 187 188 189]

[190 191 192 193 194 195 196 197 198 199]

 

[200 201 202 203 204 205 206 207 208 209]

[210 211 212 213 214 215 216 217 218 219]

[220 221 222 223 224 225 226 227 228 229]

[230 231 232 233 234 235 236 237 238 239]

[240 241 242 243 244 245 246 247 248 249]

[250 251 252 253 254 255 256 

In [4]:
c[0]+c[1]

array([[100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198],
       [200, 202, 204, 206, 208, 210, 212, 214, 216, 218],
       [220, 222, 224, 226, 228, 230, 232, 234, 236, 238],
       [240, 242, 244, 246, 248, 250, 252, 254, 256, 258],
       [260, 262, 264, 266, 268, 270, 272, 274, 276, 278],
       [280, 282, 284, 286, 288, 290, 292, 294, 296, 298]])

In [9]:
a**2

array([[ 1, 25, 36],
       [16, 25, 49]], dtype=int32)

In [23]:
b = a >= 5
a[b] = 6
a

array([[1, 6, 6],
       [4, 6, 6]])

In [25]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A.dot(B)

array([[5, 4],
       [3, 4]])

In [35]:
A

array([[8, 8],
       [0, 8]])

In [27]:
A

array([[1, 1],
       [0, 1]])

In [32]:
A

array([[8, 8],
       [0, 8]])

In [31]:
A

array([[8, 8],
       [0, 8]])

In [41]:
A+=B
A

array([[20,  8],
       [18, 32]])

In [44]:
A[::-1]

array([[18, 32],
       [20,  8]])

In [55]:
first = np.array([2,4,5,6,7,8,9,33,4,6,7])
b = first>=2
first[b] = 0
first

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Here This is Second Session

##Here This is Second Session