In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
for row in a:
    for i in row:
        print(i, end=" ")

0 1 4 9 16 25 36 49 64 81 100 121 

In [19]:
for cell in a.flatten():
    print(cell, end=" ")

0 1 4 9 16 25 36 49 64 81 100 121 

In [20]:
# c= 0
for x in np.nditer(a, order="c", flags=['external_loop']):
    print(x)
#     c+=x
# print(f"\nthe Sum of this array is {c}")

[  0   1   4   9  16  25  36  49  64  81 100 121]


In [21]:
a.ndim

2

In [7]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=x*x

In [8]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [9]:
b = np.arange(3,15,4).reshape(3,1)

In [10]:
b

array([[ 3],
       [ 7],
       [11]])

In [11]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [12]:
d = np.arange(10).reshape(2,5)
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
d = np.empty((2,3))
d

array([[2.12199579e-314, 6.36598737e-314, 1.06099790e-313],
       [1.48539705e-313, 1.90979621e-313, 2.33419537e-313]])

In [14]:
e = np.arange(12).reshape(2,3,2)
e

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [15]:
f = np.arange(100).reshape(10,10)
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])